export const API_BASE_URL = "http://192.168.1.12:5196/api";

export const STORAGE_KEYS = {
    token: "token",
    selectedGroupId: "selectedGroupId",
} as const;

import { ImageSourcePropType } from "react-native";

export const EN_PLACE_CATEGORIES = [
  { label: "Cafe", value: "cafe", icon: "cafe-outline" },
  { label: "Coffee", value: "coffee", icon: "cafe-outline" },
  { label: "Dessert", value: "dessert", icon: "ice-cream-outline" },
  { label: "Bakery", value: "bakery", icon: "ice-cream-outline" },
  { label: "Breakfast", value: "breakfast", icon: "restaurant-outline" },
  { label: "Brunch", value: "brunch", icon: "restaurant-outline" },
  { label: "Restaurant", value: "restaurant", icon: "restaurant-outline" },
  { label: "Fast Food", value: "fast_food", icon: "fast-food-outline" },
  { label: "Bar", value: "bar", icon: "wine-outline" },
  { label: "Pub", value: "pub", icon: "wine-outline" },
  { label: "Museum", value: "museum", icon: "library-outline" },
  { label: "Gallery", value: "gallery", icon: "library-outline" },
  { label: "Cinema", value: "cinema", icon: "film-outline" },
  { label: "Theatre", value: "theatre", icon: "musical-notes-outline" },
  { label: "Concert", value: "concert", icon: "musical-notes-outline" },
  { label: "Shopping", value: "shopping", icon: "bag-outline" },
  { label: "Market", value: "market", icon: "bag-outline" },
  { label: "Beach", value: "beach", icon: "sunny-outline" },
  { label: "Park", value: "park", icon: "leaf-outline" },
  { label: "Nature", value: "nature", icon: "leaf-outline" },
  { label: "Forest", value: "forest", icon: "leaf-outline" },
  { label: "Picnic", value: "picnic", icon: "leaf-outline" },
  { label: "View Point", value: "view_point", icon: "image-outline" },
  { label: "Sunset Spot", value: "sunset_spot", icon: "image-outline" },
  { label: "Trip", value: "trip", icon: "airplane-outline" },
  { label: "Holiday", value: "holiday", icon: "airplane-outline" },
  { label: "Hotel", value: "hotel", icon: "bed-outline" },
  { label: "Spa", value: "spa", icon: "flower-outline" },
  { label: "Fitness", value: "fitness", icon: "fitness-outline" },
  { label: "Walk", value: "walk", icon: "fitness-outline" },
  { label: "Hiking", value: "hiking", icon: "fitness-outline" },
  { label: "Swimming", value: "swimming", icon: "water-outline" },
  { label: "Game", value: "game", icon: "game-controller-outline" },
  { label: "Arcade", value: "arcade", icon: "game-controller-outline" },
  { label: "Photo Spot", value: "photo_spot", icon: "camera-outline" },
  { label: "Romantic Date", value: "romantic_date", icon: "heart-outline" },
  { label: "Bookstore", value: "bookstore", icon: "book-outline" },
  { label: "Study Place", value: "study_place", icon: "laptop-outline" },
  { label: "Home", value: "home", icon: "home-outline" },
  { label: "Pet Friendly", value: "pet_friendly", icon: "paw-outline" },
];
export type PlaceCategoryItem = {
  label: string;
  value: string;
  image: ImageSourcePropType;
  bgColor: string;
  borderColor: string;
  textColor: string;
  iconBg: string;
};

export const PLACE_CATEGORIES: PlaceCategoryItem[] = [
  {
    label: "Kafe",
    value: "cafe",
    image: require("../../assets/images/category-icons/cafe.png"),
    bgColor: "rgba(248, 241, 231, 0.4)",
    borderColor: "#E8D7BF",
    textColor: "#8A5A2B",
    iconBg: "#F2E4D2",
  },
  {
    label: "Tatlı",
    value: "dessert",
    image: require("../../assets/images/category-icons/dessert.png"),
    bgColor: "rgba(253, 235, 242, 0.4)",
    borderColor: "#F6C8D7",
    textColor: "#C45C8A",
    iconBg: "#FADCE8",
  },
  {
    label: "Restoran",
    value: "restaurant",
    image: require("../../assets/images/category-icons/restaurant.png"),
    bgColor: "rgba(255, 240, 234, 0.4)",
    borderColor: "#F7C9B8",
    textColor: "#D96C4A",
    iconBg: "#FCE1D6",
  },
  {
    label: "Kahvaltı",
    value: "breakfast",
    image: require("../../assets/images/category-icons/breakfast.png"),
    bgColor: "rgba(255, 240, 234, 0.4)",
    borderColor: "#F7C9B8",
    textColor: "#D96C4A",
    iconBg: "#FCE1D6",
  },
  {
    label: "Bar",
    value: "bar",
    image: require("../../assets/images/category-icons/beer.png"),
    bgColor: "rgba(244, 236, 248, 0.4)",
    borderColor: "#DCC7EA",
    textColor: "#8A5FB5",
    iconBg: "#EBDDFA",
  },
  {
    label: "Müze",
    value: "museum",
    image: require("../../assets/images/category-icons/museum.png"),
    bgColor: "rgba(238, 244, 248, 0.4)",
    borderColor: "#CBDDEA",
    textColor: "#5C7E9A",
    iconBg: "#E0ECF4",
  },
  {
    label: "Sinema",
    value: "cinema",
    image: require("../../assets/images/category-icons/cinema.png"),
    bgColor: "rgba(238, 241, 247, 0.4)",
    borderColor: "#D4DAE7",
    textColor: "#60708F",
    iconBg: "#E1E7F2",
  },
  {
    label: "Sanat",
    value: "art",
    image: require("../../assets/images/category-icons/art.png"),
    bgColor: "rgba(247, 238, 251, 0.4)",
    borderColor: "#E4CEF1",
    textColor: "#9B68C2",
    iconBg: "#EEDCF8",
  },
  {
    label: "Alışveriş",
    value: "shopping",
    image: require("../../assets/images/category-icons/shopping.png"),
    bgColor: "rgba(255, 244, 232, 0.4)",
    borderColor: "#F2D8B5",
    textColor: "#C8872F",
    iconBg: "#FBE8CF",
  },
  {
    label: "Sahil",
    value: "beach",
    image: require("../../assets/images/category-icons/vacations.png"),
    bgColor: "rgba(234, 247, 255, 0.4)",
    borderColor: "#BFE5F7",
    textColor: "#4B9BC2",
    iconBg: "#D8F0FB",
  },
  {
    label: "Doğa",
    value: "nature",
    image: require("../../assets/images/category-icons/nature.png"),
    bgColor: "rgba(238, 249, 241, 0.4)",
    borderColor: "#CBE8D2",
    textColor: "#5A9A68",
    iconBg: "#DDF1E3",
  },
  {
    label: "Otel",
    value: "hotel",
    image: require("../../assets/images/category-icons/bed.png"),
    bgColor: "rgba(247, 241, 234, 0.4)",
    borderColor: "#E4D6C8",
    textColor: "#8F7458",
    iconBg: "#EFE4D8",
  },
  {
    label: "Spa",
    value: "spa",
    image: require("../../assets/images/category-icons/spa.png"),
    bgColor: "rgba(248, 239, 248, 0.4)",
    borderColor: "#E5D3E8",
    textColor: "#A06AA8",
    iconBg: "#F0E0F1",
  },
  {
    label: "Fitness",
    value: "fitness",
    image: require("../../assets/images/category-icons/fitness.png"),
    bgColor: "rgba(236, 250, 243, 0.4)",
    borderColor: "#C9EED9",
    textColor: "#48A36D",
    iconBg: "#DCF5E7",
  },
  {
    label: "Çalışma Alanı",
    value: "study_place",
    image: require("../../assets/images/category-icons/study.png"),
    bgColor: "rgba(241, 244, 248, 0.4)",
    borderColor: "#D7DFE8",
    textColor: "#667A91",
    iconBg: "#E5EBF2",
  },
];